### ISSUE TITLE
Content doesn't take up full width of the screen.

### ISSUE THREAD

**Issue by farishkash** [ECody/TeaCozy#1]
![tea_cozy](https://user-images.githubusercontent.com/5844161/39224247-32700292-47fb-11e8-8814-e3aafafa8001.png)
![tea_cozy2](https://user-images.githubusercontent.com/5844161/39224251-34b0a1b0-47fb-11e8-8327-51d3adff5696.png)

Setting the width to 1300px for the content div is causing this, if it was set to 100% this would be fine.  If it looked fine on your computer, I am going to assume you either have a low resolution screen or are using a laptop.  This screenhost is based on an HD screen which is at least 1/3 of the market.  Something to be wary of.

**Comment by ECody** [comment]
I set the width to 100% for both the header and content classes
