### ISSUE TITLE
Always apply styles through the use of classes do not apply them directly into the element.

### ISSUE THREAD

**Issue by farishkash** [ECody/TeaCozy#3]
https://github.com/ECody/TeaCozy/blob/0e69973ed7503fa44a7f9341c83ed870e74a700e/index.html#L33

You are adding height/width to every picture.  If you had to change the dimensions, you would have to do each one.  It is much easier to apply a class and just change the class once.  As a general rule, unless absolutely necessary, always use a class.

**Comment by ECody** [comment]
moved image height and weight to style page.
