### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [ECody/TeaCozy#6]
Overall needs some improvement.

You had some structural flaws here, the website was not centered on the screen and force to the left.  The header transparent and had a gap on top.  Visually, this site did not meet expectations.

Styles should always be done through the use of the CSS file, not applied directly in the element tag.  This slowdowns efficiency and adds more to your workload.  

Alt text is a minor issue but important enough to mention.

To prepare you for the final projects, look at media queries. See if you can make this site fit inside of a mobile device by using one. You will be doing this heavily in your final projects.

https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

**Comment by ECody** [comment]
Thank you, very helpful.  I appreciate your evaluation. :-)
